
# Define job that installs Matlab and runs main_ci.
# This reads image from the master branch's images folder,
# using the GitHub remote. This runs most automatic methods
# on the selected image, failing if an error occurs.
jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command:  main_ci

workflows:
  version: 2
  workflow:
    jobs:
      - build: # only run tests if commiting to master branch!
          filters:
            branches:
              only: master

orbs:
  matlab: mathworks/matlab@0.3.0

version: 2.1
